(function () {
  window.AppData = window.AppData || {};

  window.AppData.fallbackQuestions = [
  {
    id: "dsa-easy-1",
    category: "DSA",
    difficulty: "Easy",
    type: "text",
    topic: "Arrays",
    prompt: "Explain how you would find the maximum element in an unsorted array and discuss the time complexity.",
    context: "Focus on a clean iterative approach and mention complexity tradeoffs.",
    keywords: ["iterate", "maximum", "compare", "time complexity", "O(n)"],
    idealAnswer: "Traverse the array once, keep track of the current maximum, compare each element, and return the maximum in O(n) time and O(1) extra space.",
  },
  {
    id: "dsa-easy-2",
    category: "DSA",
    difficulty: "Easy",
    type: "mcq",
    topic: "Linked List",
    prompt: "Which data structure is best suited for efficient insertion at the head?",
    context: "Pick the most direct data structure.",
    keywords: ["linked list"],
    options: ["Array", "Linked List", "Binary Search Tree", "Heap"],
    correctOption: "Linked List",
    idealAnswer: "Linked lists allow O(1) insertion at the head when you already have the head reference.",
  },{
    "id": "dsa-easy-3",
    "category": "DSA",
    "difficulty": "Easy",
    "type": "text",
    "topic": "Stack",
    "prompt": "Implement a stack using an array.",
    "context": "Basic operations.",
    "keywords": ["stack"],
    "idealAnswer": "Use list with push/pop O(1)."
  },
  {
    "id": "dsa-easy-4",
    "category": "DSA",
    "difficulty": "Easy",
    "type": "text",
    "topic": "Binary Tree",
    "prompt": "Find maximum depth of a binary tree.",
    "context": "Recursive solution.",
    "keywords": ["tree"],
    "idealAnswer": "Return 1 + max(left, right)."
  },
  {
    "id": "dsa-easy-5",
    "category": "DSA",
    "difficulty": "Easy",
    "type": "text",
    "topic": "Sorting",
    "prompt": "Explain time complexity of Merge Sort.",
    "context": "Divide and conquer.",
    "keywords": ["merge sort"],
    "idealAnswer": "O(n log n) in all cases."
  },
  {
    id: "dsa-medium-1",
    category: "DSA",
    difficulty: "Medium",
    type: "text",
    topic: "Hashing",
    prompt: "Describe how you would detect whether an array contains duplicate elements in linear time.",
    context: "Mention both the data structure and complexity.",
    keywords: ["hash set", "visited", "linear", "O(n)", "space"],
    idealAnswer: "Use a hash set to track seen values while scanning the array. If a value already exists in the set, a duplicate is found. This takes O(n) time and O(n) space.",
  },
  {
    id: "dsa-medium-2",
    category: "DSA",
    difficulty: "Medium",
    type: "text",
    topic: "Trees",
    prompt: "Explain the difference between DFS and BFS traversal and when you would prefer each one.",
    context: "Call out data structures, use cases, and depth versus breadth exploration.",
    keywords: ["stack", "queue", "depth", "breadth", "shortest path", "level order"],
    idealAnswer: "DFS explores one branch deeply using recursion or a stack, while BFS explores level by level using a queue. BFS is preferred for shortest path in unweighted graphs and level-order traversal, while DFS is useful for exhaustive path exploration and topological patterns.",
  },{
    "id": "dsa-medium-3",
    "category": "DSA",
    "difficulty": "Medium",
    "type": "text",
    "topic": "Queue",
    "prompt": "Implement queue using two stacks.",
    "context": "Amortized O(1).",
    "keywords": ["queue"],
    "idealAnswer": "Use two stacks for push/pop."
  },
  {
    "id": "dsa-medium-4",
    "category": "DSA",
    "difficulty": "Medium",
    "type": "text",
    "topic": "BST",
    "prompt": "Validate a Binary Search Tree.",
    "context": "Use min/max range.",
    "keywords": ["bst"],
    "idealAnswer": "Check node within valid range."
  },
  {
    "id": "dsa-medium-5",
    "category": "DSA",
    "difficulty": "Medium",
    "type": "text",
    "topic": "Binary Search",
    "prompt": "Search in a rotated sorted array.",
    "context": "Modified binary search.",
    "keywords": ["binary search"],
    "idealAnswer": "Check sorted half."
  },
  {
    id: "dsa-hard-1",
    category: "DSA",
    difficulty: "Hard",
    type: "text",
    topic: "Dynamic Programming",
    prompt: "Walk through how you would solve the longest increasing subsequence problem efficiently.",
    context: "Mention the optimized approach and complexity.",
    keywords: ["dynamic programming", "binary search", "tails", "O(n log n)", "subsequence"],
    idealAnswer: "A classic optimized solution maintains a tails array and uses binary search to place each number, producing an O(n log n) approach. A simpler dynamic programming solution exists in O(n^2).",
  },
  {
    id: "dsa-hard-2",
    category: "DSA",
    difficulty: "Hard",
    type: "mcq",
    topic: "Graphs",
    prompt: "Which algorithm is typically used to find the shortest path in a weighted graph with non-negative weights?",
    context: "Choose the standard single-source shortest path algorithm.",
    keywords: ["dijkstra"],
    options: ["Kruskal", "Dijkstra", "Prim", "Floyd Cycle Detection"],
    correctOption: "Dijkstra",
    idealAnswer: "Dijkstra's algorithm efficiently computes shortest paths from a source when all edge weights are non-negative.",
  },{
    "id": "dsa-hard-3",
    "category": "DSA",
    "difficulty": "Hard",
    "type": "text",
    "topic": "Mixed",
    "prompt": "Find median of two sorted arrays.",
    "context": "Binary search partition.",
    "keywords": ["median"],
    "idealAnswer": "Partition arrays."
  },
  {
    "id": "dsa-hard-4",
    "category": "DSA",
    "difficulty": "Hard",
    "type": "text",
    "topic": "Trie",
    "prompt": "Implement Trie (Prefix Tree).",
    "context": "Insert and search.",
    "keywords": ["trie"],
    "idealAnswer": "Tree with children map."
  },
  {
    "id": "dsa-hard-5",
    "category": "DSA",
    "difficulty": "Hard",
    "type": "text",
    "topic": "Sorting",
    "prompt": "Sort array based on frequency.",
    "context": "Custom comparator.",
    "keywords": ["sorting"],
    "idealAnswer": "Use hashmap + sort."
  },
  {
    id: "hr-easy-1",
    category: "HR",
    difficulty: "Easy",
    type: "text",
    topic: "Self Introduction",
    prompt: "Give a concise self-introduction suitable for the start of a professional interview.",
    context: "Structure it with background, strengths, and current goal.",
    keywords: ["background", "strength", "experience", "role", "goal"],
    idealAnswer: "A strong answer briefly covers education or experience, a few relevant strengths, and why the role is a good fit.",
  },
  {
    id: "hr-easy-2",
    category: "HR",
    difficulty: "Easy",
    type: "mcq",
    topic: "Professionalism",
    prompt: "Which response best reflects professionalism when you disagree with a teammate?",
    context: "Choose the most collaborative answer.",
    keywords: ["listen", "respectfully", "collaborate"],
    options: ["Ignore the teammate completely", "Raise your voice to make your point", "Discuss the issue respectfully and align on facts", "Escalate immediately without discussion"],
    correctOption: "Discuss the issue respectfully and align on facts",
    idealAnswer: "Professional disagreement means listening, staying respectful, and working toward evidence-based alignment.",
  },
  {
    id: "hr-medium-1",
    category: "HR",
    difficulty: "Medium",
    type: "text",
    topic: "Conflict Resolution",
    prompt: "Describe a situation where you resolved a conflict in a team. How did you approach it?",
    context: "Use a STAR-style structure and focus on communication.",
    keywords: ["situation", "task", "action", "result", "communication", "resolution"],
    idealAnswer: "A strong answer explains the situation, your responsibility, the specific actions you took to de-escalate or align the team, and the positive outcome.",
  },
  {
    id: "hr-medium-2",
    category: "HR",
    difficulty: "Medium",
    type: "text",
    topic: "Career Motivation",
    prompt: "Why do you want to work at this company, and how does it fit your long-term goals?",
    context: "Connect company values, role relevance, and growth motivation.",
    keywords: ["values", "growth", "impact", "role", "long-term"],
    idealAnswer: "Good answers tie the company's mission and team to the candidate's strengths and long-term development goals.",
  },
  {
    id: "hr-hard-1",
    category: "HR",
    difficulty: "Hard",
    type: "text",
    topic: "Leadership",
    prompt: "Tell me about a time you led a team through uncertainty or changing priorities.",
    context: "Highlight decision-making, communication, and outcomes.",
    keywords: ["leadership", "prioritize", "stakeholders", "communication", "outcome", "adapt"],
    idealAnswer: "The answer should show how you set direction, kept stakeholders informed, adapted plans, and delivered results despite ambiguity.",
  },
  {
    id: "hr-hard-2",
    category: "HR",
    difficulty: "Hard",
    type: "mcq",
    topic: "Ownership",
    prompt: "What is the best response when you realize you made a mistake that affects the team?",
    context: "Choose the most responsible behavior.",
    keywords: ["own", "correct", "communicate"],
    options: ["Hide it and hope nobody notices", "Own the mistake, communicate it early, and propose a fix", "Blame the process immediately", "Wait until the deadline passes to mention it"],
    correctOption: "Own the mistake, communicate it early, and propose a fix",
    idealAnswer: "Strong ownership means surfacing the issue early, taking responsibility, and helping drive the correction.",
  },
  {
    id: "sd-easy-1",
    category: "System Design",
    difficulty: "Easy",
    type: "text",
    topic: "Scalability Basics",
    prompt: "What is the difference between vertical scaling and horizontal scaling?",
    context: "Mention capacity, machines, and tradeoffs.",
    keywords: ["vertical", "horizontal", "single machine", "multiple machines", "scale"],
    idealAnswer: "Vertical scaling adds resources to one machine, while horizontal scaling adds more machines or instances to distribute load.",
  },
  {
    id: "sd-easy-2",
    category: "System Design",
    difficulty: "Easy",
    type: "mcq",
    topic: "Caching",
    prompt: "What is the main purpose of a cache in a web system?",
    context: "Pick the clearest system-level benefit.",
    keywords: ["latency", "performance"],
    options: ["Increase response latency", "Reduce repeated data fetch cost and improve performance", "Replace the network entirely", "Guarantee zero downtime"],
    correctOption: "Reduce repeated data fetch cost and improve performance",
    idealAnswer: "Caching helps serve repeated requests faster and reduces backend load.",
  },
  {
    id: "sd-medium-1",
    category: "System Design",
    difficulty: "Medium",
    type: "text",
    topic: "Load Balancing",
    prompt: "Explain why a load balancer is useful in a distributed system.",
    context: "Talk about traffic distribution, availability, and resilience.",
    keywords: ["distribute", "traffic", "availability", "fault tolerance", "instances"],
    idealAnswer: "A load balancer distributes traffic across instances to improve reliability, prevent overload, and help the system stay available when nodes fail.",
  },
  {
    id: "sd-medium-2",
    category: "System Design",
    difficulty: "Medium",
    type: "text",
    topic: "Databases",
    prompt: "When would you choose a NoSQL database over a relational database?",
    context: "Mention schema flexibility, scaling, and access patterns.",
    keywords: ["schema", "flexible", "scaling", "document", "access patterns"],
    idealAnswer: "NoSQL is a fit when you need flexible schemas, large-scale horizontal distribution, or data models like key-value or document storage that suit the access pattern.",
  },
  {
    id: "sd-hard-1",
    category: "System Design",
    difficulty: "Hard",
    type: "text",
    topic: "High Availability",
    prompt: "Design a high-level architecture for a URL shortener that needs to handle large read traffic.",
    context: "Discuss components, storage, scaling, and caching.",
    keywords: ["api", "database", "cache", "read heavy", "replication", "load balancer"],
    idealAnswer: "A high-level design would include stateless API servers behind a load balancer, a durable primary data store with replication, caching for popular URLs, and a key generation strategy.",
  },
  {
    id: "sd-hard-2",
    category: "System Design",
    difficulty: "Hard",
    type: "mcq",
    topic: "Reliability",
    prompt: "Which approach most directly improves system resiliency during instance failure?",
    context: "Choose the design that tolerates node loss.",
    keywords: ["redundancy", "failover"],
    options: ["Single server deployment", "Multiple redundant instances with failover", "Disable monitoring alerts", "Store everything in memory on one node"],
    correctOption: "Multiple redundant instances with failover",
    idealAnswer: "Redundant instances and failover mechanisms allow service continuity even when a node fails.",
  },
  ];
})();
